---
title: "LIT REVIEW"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lit-Review

### 1. Cheng, Hang Sheng. "Statistical Estimates of Elasticities and Propensities in International Trade: A Survey of Published Studies." Staff Papers (International Monetary Fund), vol. 7, no. 1, 1959, pp. 107--158. JSTOR, www.jstor.org/stable/3866125.

-   intro: "The present paper is intended as a contribution toward meeting this need. Part I is an index, according to country or area, of estimates of elasticity and propensities taken from 42 books and articles published in the period 1937 to 1957. These sources are described in Part II. The numbers in parentheses-e.g., exports of food (30), (31), under United Kingdom-in Part I, are references to the sources given in Part II for the estimated elasticity or propensities related to the topic.' Each description in Part II sets forth the purpose and scope of the study, the variables and the methods used in the statistical and the tests of significance used (if any), and the conclusions drawn by the author. A quick look at these notes may help the reader to decide whether a study is likely to give him the information that will be useful to him." (pg 1-2)
-   Notes: Part I (Index of Statistical Estimates According to Area or Country) shows all the counties and the number in parentheses is the article in part II (Bibliography Notes) that the statistics is drawn from.
-   <https://doi.org/10.2307/3866125>

### 2. Balassa, Bela. "Tariff Reductions and Trade in Manufacturers among the Industrial Countries." The American Economic Review, vol. 56, no. 3, 1966, pp. 466--473. JSTOR, www.jstor.org/stable/1823779.

-   "This paper uses empirical evidence to examine the proposition advanced by Lawrence B. Krause that the establishment of the Common Market will seriously harm U.S. exports because "dominant suppliers" in EEC countries receive increased protection from the averaging of national tariffs. Subsequently, the results are used to reinterpret the traditional conclusions regarding the effects of tariff reductions on the domestic economy, and additional tests are offered to indicate the predominance of intra-industry-as against inter-industry specialization in trade in manufactures among the industrial countries." -Notes: This article looks at tariffs among the industrial counties (US, Belgium, France, Germany, Italy, and Netherlands). They use export data from 1958 of 91 manufacturing industries. The years focused on are 1958 and 1963.

### 3. Chenery, Hollis B. "Patterns of Industrial Growth." The American Economic Review, vol. 50, no. 4, 1960, pp. 624--654. JSTOR, www.jstor.org/stable/1812463.

-   "An increase in per capita income in a country is normally accompanied by a rise in the share of industrial output. The accepted explanation for this relationship is the change in the composition of demand,of which the decline in the share of food (Engel's Law) is the most not-able feature. However, this over-all relationship does not necessarily apply to every individual country. Within limits, the changing composition of domestic demand can be offset through foreign trade. A country having a continuing comparative advantage in primary production may therefore reach a high level of income without an increase in the share of industry in total output. Because of the diversity of natural resources, we should not expect to find uniform patterns of growth in all countries.'Evidence from several sources suggests a closer and more pronounced relationship between levels of income and industrial output than would be predicted from the change in demand alone. Kuznets' comparison of some 50 countries [13] shows a marked increase of manufacturing with rising per capita income, as did the earlier analyses of Bean[1] and Clark [2]."

-   Notes: The author said on page 630 that, "the estimation of sector growth functions in the present paper is therefore based on data for a number of countries, mainly for years between 1950-1956." The paper takes into account both imports and exports. Dr. Hollis also uses 51 countries including the US. The paper seems to expand on a growth model equation to include sector growth, international trade, and intermediate goods. On page 631, the author explains the collected data in the tables 1-3. In table two (page 633) it lists all the sectors: Food and beverages. tobacco, textiles, clothing, wood, paper, printing, leather, rubber, chemicals, petroleum products, petroleum products II, Nonmetallic minerals, metals, machinery, and transport equipment.

### 4. Finger, J. M. "Gatt Tariff Concessions and the Exports of Developing Countries--United States Concessions at the Dillon Round." The Economic Journal, vol. 84, no. 335, 1974, pp. 566--575. JSTOR, www.jstor.org/stable/2231040.

-   "AT the 1960-61 GATT tariff conference (The Dillon Round) the United States negotiated with the European Economic Community and 11 other developed countries (DC) as well as with six less developed countries (LDC)(Cambodia, Haiti, India, Israel, Pakistan and Peru) and agreed to reduce its duties on products covering some \\\$2 billion of imports in 1960. While this 20 % reduction of tariffs on some 20 % of dutiable imports was small compared with the 35 % cut on almost 55 % of dutiable imports achieved in the more recent Kennedy Round, they were more extensive, both in terms of the magnitude of the reductions and extent of import coverage, than the reductions achieved in any of the previous five GATT rounds except the first,in Geneva in 1947."

-   Notes: The author used estimates of the effects of the concessions on the US imports, with separate figures for imports from developed countries and from the less developed countries mentioned in the intro above. He uses import statistics from 1960 and 1965 and compares the data. The differences between the two years are his estimates used throughout the paper. The import data was separated into materials and manufactured (as seen in table I on page 568). His findings on the comparison of the developed and developing counties baskets are summarized in table II (page 571). Looks at the effects of the Kennedy round tariff concessions

-   Data Sources: Average proportional tariff change is from UNCTAD (1968), p.208. Figures are the average over all manufactured goods and cover all five stages of the reduction. "The samples of products from which the effects of the Kennedy Round cuts were estimated were based on a random sample of tariff line (7-digit code)items drawn by the UNCTAD Secretariat to estimate pre- and post-Kennedy Round tariff averages. In constructing the UNCTAD sample care had been taken to make the sample comparable across countries, i.e. though lack of compatibility at the tariff line level had made it necessary to define a separate sample for each country, in terms of that country's tariff nomenclature, in constructing the UNCTAD samples for each country care had been taken to make them as compatible as possible." (pg 90) The UNCTAD sample was drawn using probability weights based on total imports of OECD countries. It is described in UNCTAD (I968), pp. IO f., 44 f

### 5. Kreinin, Mordechai E. "Effect of Tariff Changes on the Prices and Volume of Imports." The American Economic Review, vol. 51, no. 3, 1961, pp. 310--324. JSTOR, www.jstor.org/stable/1814161.

-   Intro: For the past 25 years the United States has been granting tariff concessions to foreign nations under authority provided by the Reciprocal Trade Agreements Act of 1934. Negotiations leading to these concessions were conducted on a bilateral basis during the prewar years, and shifted to the multilateral framework of the General Agreement on Tariffs and Trade (GATT) in 1947. But throughout the entire period they were subject to the unconditional most favored nation principle under which a concession granted to any one country is immediately applicable to all other sources of supply. In total, these concessions had a sizeable effect on the United States tariff level, reducing the ratio1 of duties collected to the value of dutiable imports by 50 percent between 1933 and 1953:Concessions made in all trade agreements apply to articles which accounted for 93.4 per cent of the total dutiable imports in 1952.... The average ad-valorem equivalent of the duties on total dutiable imports (weighted by 1952 data) before any trade agreements were in effect was 24.4 per cent. The average at January 1, 1945, rates was 17.9 per cent; and as of January 1, 1953, it was 12.2 per cent [17, p. 3]. Although overshadowed by the substantial rise in income during the past generation, such a large decline in the level of protection could not fail to have some effect on the volume of U.S. imports. This article utilizes data from the two most recent GATT negotiations, conducted in 1955 and 1956, to examine the effect of the United States tariff-reduction program on the prices and volume of imports subject to tariff concessions. After comparing the results to those obtained by other students of the subject, the data are used to draw policy conclusions and to measure roughly the gain in welfare and the loss of employment resulting from the tariff cuts."

-   Notes: paper looks at data from the GATT negotiations in 1955 and 1956 to examine the effect of the US tariff reduction program on the prices and volume of imports subject to tariff concessions. The author looks at the price and quantity changed of imported all commodities and all commodities- but excluding textiles (1954 and 1956) and the changes from all commodities and finished manufactured imports. These groups were all separated further into sub-categories: a reduced group (products where tariffs were reduced) and a non-reduced group (products where were not subject to tariff reductions). Results and grouping can be seen in table I on page 315.

### 6. Leamer, Edward E. "Nominal Tariff Averages with Estimated Weights." Southern Economic Journal, vol. 41, no. 1, 1974, pp. 34--46. JSTOR, www.jstor.org/stable/1056094.

-   Main Point of Intro: "The intent of this paper is to estimate a model of international trade and to use that model to construct tariff averages. In section 1 we shall describe a fairly complete trade dependence model that includes tariffs and that allows tariff elasticities to vary from commodity to commodity. The model is estimated using cross-section 1958 data and the results are reported in section 2. These estimates are used in section 3 to compute ahandful of different tariff averages and corresponding elasticity averages. Section 4 contains brief concluding remarks."

-   Notes: Paper uses tariff and trade data from \*Atlantic Tariffs and Trade\*. He used the tariff averages from 1958 for 13 Atlantic area countries (Austria, Berelux, Canada, Denmark, France, Germany, Italy, Norway, Portugal, Sweden, UK, and USA) and 28 different commodities listed in Table I (page 37)

### 7. Conybeare, J. (1983). Tariff protection in developed and developing countries: A cross-sectional and longitudinal analysis. International Organization, 37(3), 441-467.

-   Abstract: "Four political models (the international system, rational domestic economic policy, intra-govemmental politics, and interest group influence) may explain the cross-national structure of average nominal levels of tariffs on manufactures. Using available data measuring or approximating the explanatory variables for the time periods 1902 and 1971, selected hypotheses were tested in regression equations. The 1971 tariff levels are best predicted by rational economic policy variables while for 1902, international power variables provide the best predictions of the tariff. In general, the causal forces influencing the cross-national pattern of tariff levels appear to have shifted in the 20th century from those indicating international power to those measuring domestic politico-economic development. These results provide evidence relevant to some of the general propositions about size and development suggested by the contemporary political economy literature. They also lend support to those who argue that a rising level of international interdependence has resulted in long-term changes in the pattern of influences on national public policies."

-   NOTES: Conybeare collected average nominal tariff levels for manufactures for 35 countries from 1958-1971. For all the countries the author listed where he got the data in table 1 on page 444. He got the United States data from GATT. He listed the following as his sources for the 1958-71 tariffs: Asian Development Bank, Southeast Asia's Economy in the 1970s (London: Longman, 1971), pp. 250-51; B. Balassa et al., The Structure of Protection in Developing Countries (Baltimore: Johns Hopkins Press, 1971), p. 54; Balassa, "Tariffs and Trade in the Andean Common Market," Journal of Common Market Studies 12 (1973), p. 177; J. N. Bhagwati and P. Desai, India: Planning for Industrialization (London: Oxford University Press, 1970), p. 477; L. Gamir, "The Calculation of Effective Rates of Protection in Spain," in H. G. Grubel and H. G. Johnson, eds., Effective Tariff Protection (Geneva: GATT, 1971), p. 206; GATT, Basic Documentation for the Tariff Study (Geneva, 1972); Industries Assistance Commission, Annual Report 1974-75 (Canberra: Australian Government Publishing Service, 1975), p. 112; J. de Melo, "Estimating the Costs of Protection: A General Equilibrium Approach," Research Program in Development Studies Discussion Paper no. 62, Woodrow Wilson School, Princeton University (Princeton, N.J., 1976), p. 13.

-   <https://www.jstor.org/stable/2706451?seq=1#metadata_info_tab_contents>

### 8. Finger, J. M. "Effects of the Kennedy Round Tariff Concessions on the Exports of Developing Countries." The Economic Journal, vol. 86, no. 341, 1976, pp. 87--95. JSTOR, www.jstor.org/stable/2230953.

-   Intro: "At the Kennedy Round the major industrial countries agreed to tariff reductions of about one-third of the initial level on about one-third of their total or two-thirds of their dutiable imports - the largest set of concessions negotiated at any of the six completed GATT rounds. This paper summarizes the results of a study of the effects on manufactured imports (SITC 5-8 less 67, 68) of the Kennedy Round tariff concessions implemented by the United States, the EEC and Japan. In particular it is concerned with the supply-lag hypothesis that developing-country exports will not respond as strongly as developed-country exports to the marginal profit incentive of the tariff cuts. The methodology of the study was to compare the change of industrial- country imports of a random sample of products on which large tariff reductions were made with the record of another sample of similar imports on which tariffs were changed by smaller amounts. The extension of the familiar "reduced group, non-reduced group" methodology2 to allow for tariff changes in the 'control group' was made necessary by the inclusiveness of the Kennedy Round cuts."

-   Notes: This Paper and the paper Finger written that is listed above (\\\#4) are very similar in the method and data collected minus that this paper focuses on the Kennedy Round rather than the Dillon Round. Finger uses tariff concessions implemented by the US, the European Economic Community (EEC), and Japan. He test imports the EEC, US, and Japan from developing countries and from developed countries. The samples of products from the effects of the Kennedy Round cuts were estimated were based on a random sample of tariff lines. The observations covered about 15% of the items on which concessions were made from each country.

### 9. Hartigan, James C. "The U.S. Tariff and Comparative Advantage: A Survey of Method." Weltwirtschaftliches Archiv, vol. 117, no. 1, 1981, pp. 65--109. JSTOR, www.jstor.org/stable/40438552.

-   Intro: "The pursuit of the sources of comparative advantage for a country is closely related to the analysis of the welfare and income distribution effects of trade policy. In other words, as trade barriers are reduced, an economy approaches its free trade production pattern, and comparative advantage is disclosed. Thus, studies of comparative advantage and analyses of trade policy are identical, although this is frequently misconstrued. Accordingly, this paper surveys both the studies that focus on U.S. comparative advantage, and those concerned with trade policy. A major tenet of this paper is that a general equilibrium approach to all these issues is mandated, in view of the potentially pervasive impact of trade on an economy. This can be performed through the explicit simulation of a general equilibrium model, or through a regression analysis that incorporates simultaneity. When there is mutual determinacy of trade barriers and comparative advantage, it is permissible to regress each as a function of their determinants in a two-stage procedure. Thus, regression is a substitute for a general equilibrium analysis when it is completely specified. Implicit in the selection of material for this paper is the assumption of the validity of the factor proportions theory of trade. To this end, applications of the classical, or differential productivity, theory of trade are not considered1."

### 10. Golub, Stephen S., and J. M. Finger. "The Processing of Primary Commodities: Effects of Developed-Country Tariff Escalation and Developing-Country Export Taxes." Journal of Political Economy, vol. 87, no. 3, 1979, pp. 559--577. JSTOR, www.jstor.org/stable/1832023.

-   Abstract: "Both DC (developed country) tariffs and LDC (developing country) export taxes are "escalated" to protect local processors of primary commodities. The paper develops an analytical model of north-south commodity trade which is used to estimate the effects of reciprocal elimination of these trade barriers for eight commodities. It is estimated that processing would increase by 9 percent in the LDCs and decline by less than 1 percent in the DCs. The LDC export revenue for the eight-commodity sample would increase by 11 percent, or just over \\\$1 billion (based on 1973 trade flows), which is considerably more than the estimated effect of the Generalized System of Preferences."

-   Purpose of Paper: "In this paper we will estimate and compare the magnitudes and effects of LDC export taxes with those of DC import tariffs. Of particular interest are the effects on the amounts of processing per- formed in LDCs and DCs and on the levels of trade of primary and processed commodities. In order to estimate such effects, it was necessary to construct a model capable of isolating them. While tariff escalation is usually studied by calculating effective rates of protection, the effective-rate concept breaks down when the small-country assumption is dropped. In the context of north-south trade in commodities such as cotton and coffee, it is clearly not tenable to assume that either side is too small to influence world prices. Thus the model we developed is capable of determining resource flows and trade patterns without assuming that either the DCs or the LDCs take world prices as given. The point of this analysis is to suggest the possibility of the simul- taneous reduction of LDC export taxes on primary commodities and DC import tariffs on processed commodities. Unfortunately, sym- pathy for improving the economic lot of the poorer countries has become almost synonymous with voicing demands for unilateral concessions by the developed world. But while this "confrontation" has produced an acrimonious north-south dialogue, few substantive changes in economic policy have resulted. If areas of common interest between LDCs and DCs can be found, and if their benefits can be shown to be large relative to the LDC gains from unilateral gifts, perhaps the north-south dialogue can be diverted toward a more constructive path. Reductions of DC tariffs and LDC export taxes on raw and processed commodities is one such avenue of mutual interest." (pg 561)

-   SOURCES - The average tariff's were in all but one case (coffee) calculated from Yeats's 1976 tabulation. For coffee, the tariffs were obtained from tariff tables for the EEC, United States, and Japan. The export-tax information was obtained from a U.S. government interagency report on export restrictions (U.S. Government 1976). Export taxes and tariffs were averaged across countries using weights based on 1973 trade flows. The trade and production effects use 1973 trade flows (OECD 1973) and production levels (FAO 1976) as the base for their model. They look at 8 products: Copra, Rubber, cocoa, cotton, wool, leather, wood, and coffee.

### 11. Kreinin, Mordechai E. "The Effect of Exchange Rate Changes on the Prices and Volume of Foreign Trade (L'effet Des Modifications Du Taux De Change Sur Les Prix Et Le Volume Du Commerce Extérieur) (El Efecto De Las Variaciiones Del Tipo De Cambio Sobre Los Precios y El Volumen Del Comercio Exterior)." Staff Papers (International Monetary Fund), vol. 24, no. 2, 1977, pp. 297--329. JSTOR, www.jstor.org/stable/3866575.

-   ABSTRACT: "This paper utilizes the exchange rate experience of the Smithsonian Agreement period to investigate the effect of exchange rate changes on the prices of traded goods and on trade flows of the United States, Canada, Japan, and several Western European countries. In contrast to econometric investigations of the same topic, this study employs the control country approach to isolate the effect of exchange rate adjustments from the effects of other factors on the prices and volumes of traded goods. This approach necessitates the use of percentage changes (from 1970 to 1972, and from 1970 to 1973) in bilateral exchange rates and bilateral trade flows between the country under study and each of its main trading partners. For each of the seven countries studied, the results include (1) an estimated pass-through effect of the exchange rate on imports and exports; (2) an estimated effect on the volume of imports and exports; (3) the change in the terms of trade; (4) the implied elasticities of demand for imports and of foreign demand for the country's exports; and (5) the estimated elasticity of substitution in its market between third country suppliers for price changes occurring between 1970 and 1972, and between 1970 and 1973. The results conform well to theoretical expectations. Where comparisons are possible, they are consistent with estimates obtained by other methods. The computations yielded (at an intermediate stage) estimates of the degree of trade overlap among exporting and importing countries. Although trade overlap is not related to the subjects covered in this article, these results may prove useful to other investigators (for example, in developing or testing theories of the commodity composition of trade); they are presented in the Appendix."

-   Comment: original paper is in Spanish, this is a translated version. Kreinin uses data from 16 OECD countries to find the percent changes in US dollar exchange rates, 1970-72, and indices of industrial production and consumer prices, 1972. His source: The exchange rate changes were calculated from the Federal Reserve Bulletin VOL. 59 (January 1973), p.A93. Consumer price indices were taken from Organization for Economics Cooperation and Development (OECD), Main Economic Indicators (August 1975). Indices of industrial production were taken from United Nations Monthly Bulletin of Statistics, Vol. 30 (April 1976), Table 10, pp 22-23.

-   "Only high disaggregated products are homogeneous enough for the quantity information to be meaningful. For the United States (as the K country), this study draws on the U. S. Treasury's Trade Statistics U.S.A. data tapes for 1970 and 1972. Based on the seven-digit Schedule A (import) and Schedule B (export) classifications, they include value and volume data for individual products imported to, and exported from, the United States by source country and destination country, respectively. For all other countries, the somewhat more aggregated (four-digit or five-digit Standard International Trade Classification (SITC) of commodities) OECD trade data tapes were used as the primary data source. To check on the comparability of the data, the pass-through effect of U. S. imports was estimated twice in the same manner using both sets of data. The results were, indeed, very similar: in the 35-65 per cent range using the U. S. census data, and in the 40-70 per cent range using the OECD data." (Pg. 315)

### 12. Harrigan, James. "The Volume of Trade in Differentiated Intermediate Goods: Theory and Evidence." The Review of Economics and Statistics, vol. 77, no. 2, 1995, pp. 283--293. JSTOR, www.jstor.org/stable/2109865.

-   ABSTRACT: "The paper develops a model of trade in differentiated intermediate goods, and shows how the structure of the importing country's production will influence gross bilateral import volumes. A regression equation directly implied by the model is estimated using disaggregated bilateral trade data for the OECD countries in 1985. The data reject the model. A more general model suggested by the theory establishes strong links between a country's factor endowments and its gross trade volume. This model is dominated statistically by a fixed effects model, and does not substantially alter the conclusions of earlier empirical studies about openness to trade in manufactured goods."

-   Notes: In the introduction, Harrigan said "Using disaggregated data on trade and production within the OECD in 1985, I conclude that the model is not consistent with the data. A more general but less rigorously derived empirical model demonstrates that gross imports depend systematically on the importing country's factor endowments, which suggests that the importer's structure of production does influence the volume of trade." (pg. 283). All the data are from 21 OECD counties: Canada, the United States, Japan Australia, New Zealand, Austria, Belgium, Britain, France, Denmark, Finland, France, West Germany, Greece, Ireland, Italy, the Netherlands, Norway, Spain, Sweden, and Turkey. He uses the nine categories of the two-digit level of the international Standard Industrial Classification (ISIC), except for ISIC 353, Petroleum refineries. The categories are: Food, Apparel, Wood, Paper, Chemicals, Glass, Metals, Machinery, Other. A more detailed list of these categories with classification numbers and definitions can be found on page 287.

### 13. Helpman, Elhanan "Imperfect Competition and International Trade: Evidence from fourteen Industrial Countries". \*Journal of the Japanese and International Economies\*, Volume I, 62-81. 1987. Department of Economics, Tel Aviv University.

-   Abstract: "Three hypotheses that emerge from a theoretical model are discussed. Two of them concern the behavior of the share of intra-industry trade while the third concerns the volume of trade. One is that in cross-country comparisons the larger the similarity in factor composition, the larger the share of intra-industry trade. The second is that in time series data the more similar the factor composition of a group of countries becomes over time, the larger the share of intra-industry trade within the group. The third is that changes over time in relative country size can explain the rising trade-income ratio. All three hypotheses are consistent with the data. J. Japan. Int. Econ., March 1987, 1(1), pp. 62--81. Department of Economics, Tel Aviv University, Ramat-Aviv, Tel Aviv 69978, Israel." Helpman looks at imperfect competition and International trade and uses evidence from 14 different countries (1956-1981 and 1970-1981)

-   Data Source: The countries in the sample are Canada, the US, Japan, Austria, Belgium- Luxembourg, Denmark, France, Germany, Ireland, Italy, the Netherlands, Sweden, Switzerland, and the UK. "The time series of these calculations, for the years 1970-1981, is reported in the first column of Table IV. The values are based on the four-digit SITC data and they were calculated for the sample of the 14 industrial countries that are listed at the bottom of Table I, using all sectors in the calculation (not the manufacturing vectors only). " (pg 77).

-   [https://doi.org/10.1016/0889-1583(87)90027-X](https://doi.org/10.1016/0889-1583(87)90027-X%5D(https://doi.org/10.1016/0889-1583(87)90027-X)%7B.uri%7D)

### 14. Paul Krugman, 1992. "Geography and Trade," MIT Press Books, The MIT Press, edition 1, volume 1, number 0262610868, December.

-   Intro: "I have spent my whole professional life as an international economist thinking and writing about economic geography, without being aware of it," begins Paul Krugman in the readable and anecdotal style that has become a hallmark of his writings. Krugman observes that his own shortcomings in ignoring economic geography have been shared by many professional economists,primarily because of the lack of explanatory models. In Geography and Trade he provides a stimulating synthesis of ideas in the literature and describes new models for implementing a study of economic geography that could change the nature of the field.Economic theory usually assumes away distance. Krugman argues that it is time to put it back - that the location of production in spaceis a key issue both within and between nations.Paul Krugman is Professor of Economics at the Massachusetts Institute of Technology. He has been a consultant to the International Monetary Fund,the World Bank, the United Nations, the Trilateral Commission, and the U.S. State Department. He isa member of the Group of Thirty. His books include the recent bestselling Age of Diminished Expectations: U.S. Economic Policy in the 1990s."

-   Comment: This is a book, I would skip to the chapter called "some empirical evidence" can be found in the SU Library ISBN: 0262111594 9780262111591 or Bird 4th floor.

### 15. Stern, R. M., Francis, J. H. and Schumacher, B., 'Price Elasticities in International Trade: A Compilation and Annotated Bibliography', Seminar Discussion Paper No. 62 (Ann Arbor, Department of Economics, University of Michigan, 1975).

-   Abstract of chapter 1: Abstract Estimates of the response of imports and exports to price changes are interesting and important for a variety of purposes. On an aggregate level, the investigator or policy maker may wish to know what effects exchange-rate realignments may have on the trade balances of different countries. Or, put differently, the problem may be to determine the exchange-rate change required to eliminate a trade imbalance of a given size. Exchange-rate changes will also affect aggregate income and employment as a consequence of the expenditure shifts that occur and that result in the expansion or contraction of a country's export and import-competing industries. To cope with issues like these, information on the relevant elasticities of demand and supply is necessary.

-   Data Sources: The tables used gives a summary of the number of estimates available their range, and 'best' point estimates for total imports, total exports, and for the one-digit Standard International Trade Classifications (SITC) groupings that comprise these totals. The Authors used estimates of import- and export- demand elasticities for the 18 countries for which trade and tariff data have been compiled by the GATT in its *Basic Documentation for the Tariff Study (1974).* These countries were chosen because the GATT documentation will serve as the basis for evaluating concessions to be made in the Tokyo Round of the Multilateral Trade negotiations. The SITC categories used in Table 2.1 are SITC 0+1 Food, beverage, and tobacco; SITC 2+4 Crude materials; oils and fats; SITC 3 Mineral fuels; SITC 5-9 Manufactured goods, SITC 0-9 Total imports (exports). More about the data can be found in Chapter 2: *Synthesis of Selected Elasticity Results*.

-   Notes: all information gathered are from previews found in the link below of every chapter. Book can be found on the 4th floor of Bird Library. [HF1007 .S82, Bird-4th Floor](https://syracuse.summon.serialssolutions.com/2.0.0/link/0/eLvHCXMwY2AwNtIz0EUrEwyMk4GxbWZsmGyaZpxommKabJpilpKSnJRsbGRhAd4j5hdo6uFj7hxg6QIdyShG7N_WK66EXByFc2LGGFjtg7dTG1qag1b2BQYYgjvp5qA7TAyMzaFn7cD4oGvZgGYmJpcWpyLVJ26CDCygPQZCDEypeSIMzja5iUXZduAL2BVSga1Z0EJn0DmnNvpgCYXMPAWIkkzk4TuFkqLElFSoGlEGOTfXEGcPXZh18VA_xUOcbCTGwALs6KdKMCiYmJslmRqaJRqmGaWZGIN2pCYBextGxolJKYmp5kmWkgziOAyRZFDAkIEFUryxuaWhhYUUTs3SDFzAQIOOK8gwsKYB032qLCJ85MChCQAQCoWr)

-   The [Table of Contents](https://www.palgrave.com/gp/book/9781349031399) and the previews of every chapter.

### 16. FIELD, ALFRED J., JR. A Multi - Regional, Multi - Commodity Descriptive And Econometric Analysis Of World Trade, 1953-1964. (volumes I And Ii), Iowa State University, Ann Arbor, 1967. ProQuest, <https://libezproxy.syr.edu/login?url=https://www.proquest.com/dissertations-theses/multi-regional-commodity-descriptive-econometric/docview/288305718/se-2?accountid=14214>.

-   Intro: "International economic relations constitute a vital and often explosive element of current domestic and international economic questions. At a time when the entire world is in the process of rapid transformation, the importance of successful international relations is paramount. The coexistence of the developed regions of the world with the developing countries in Asia, Africa, and Latin America provides a basis for political and economic tensions which can only be overcome if the needs of those larger portions of the world population can be met. The gap between developed and less- developed countries has been growing, adding further to international tensions. The problem of underdeveloped is continually affected by the low price levels and economic instability in the markets for primary products. This instability is basically the result of the sensitivity of these products to cyclical fluctuations in income and output of the industrial countries and to the disturbance which often arise from "shortsightedness of national policy makers in international trade" (163,8).1 Supplementing these sources of instability are disturbances emanating from changes in the supply situation which are often the result of the non-controllable factors of nature.1 Restrictions on imports and become more common as a number of the developing countries have taken defensive actions to inhibit the expansion of the import trade.2 The multiple problems of the less-developed countries have been accompanied by concomitant balance-of-payments problems in the developed countries of the world. These developing nations in the international trade field have been given increased attention within the framework of the General Agreement on Tariffs and Trade (G.A.T.T.), foreign aid programs, the international Monetary Fund, and recently by the United Nations Conference on Trade and Development. In addition to the work of the international agencies, a major trade promoting effect has been attempted through the Kennedy round of tariff negotiations under the authority of the United States Trade expansion Act of 1962. The major aims of these programs have been to help sustain the current high rates of growth of international trade and the expansion of the export earning of the developed counties. The effectiveness of government programs and policy decisions in international trade is heavily dependent upon an accurate understanding and evaluation of international markets on which the level and pattern of fo reign trade depend. Thus there exists a strong case for rigorous investigation in to the trends in commodity composition and geographical concentration of world trade where sufficient statistical material is available . An accurate in sight as to what governs the size and composition of imports and exports is essential to farsighted policy decisions. An examination of the available statistics showed a noticeable lack in a consistent multi-regional, multi-commodity time series presentation of international trade data necessary for such an analysis. It appeared extremely desirable to develop a matrix o f world trade flows for the1950's and 1960's within which the relative changes in world trade could be examined, and which could be extended each year as new data became available . Consequently, the preparation of such a trade matrix was undertaken."

-   Objective of the Study: "The main purpose of th is study is the descriptive and quantitative analysis of the most important changes which have taken place with in the network of world trade over the period 1953 to 1964. The study was carried out using the aforementioned multi-commodity, muti-regional framework. The objectives of the study are 1) to present a largely descriptive analysis of the changes in both the commodity com position and geographical pattern of world trade from 1953 to 1964, 2) to identify and describe the variables influencing the development and the present status of the network of world trade, 3) to develop a theoretical framework with in which key variables and relationships can be quantitatively examined, and 4) to estimate the parameters of the relevant variables, specified by the theoretical construct, through statistical analysis." (pg. 8) Full objective ranges from page 8-10.

-   Comments: The study consist of 3 parts: a literature review, a descriptive analysis, and an economic analysis of total trade flows. The analysis starts in Chapter 3 or page 57.

-   Data: focuses on the US imports and exports from 1953-1964.

### 17. GOLDSTEIN, MORRIS, and MOHSIN S. KHAN. " Large Versus Small Price Changes and the Demand for Imports". IMF Staff Papers 1976.001 (1976), A007. \< <https://doi.org/10.5089/9781451956436.024.A007>.

-   Abstract: "The purpose of this paper is twofold: first, to provide new estimates of the aggregate import demand equations for 12 industrial counties, using quarterly data on the relevant variables for the period 1955-1973; and second, to examine empirically whether the elasticiity of import with resprect to relative prices, 1 and the speed at which actual imports adjust to the desired level are both independent of the size of the relative price change."

-   Notes: The counties used are: Belgium, Denmark, France, Finland, Germnay, Netherlands, Italy, Japan, Norway, Sweden, the United Kingdom, and the United States. The authors uses quarterly import data and tests import demand functions. The data is taken form Organization for Economic Cooperation and Development (OECD), \*Main Economic Indicators\*, various issues.

-   Website link: <https://www.elibrary.imf.org/view/journals/024/1976/001/article-A007-en.xml> I found this article on the IMF eLibrary. I could not download it but you can read it on the website linked above.

### 18. Balassa, Bela. "Tariff Protection in Industrial Countries: An Evaluation." Journal of Political Economy, vol. 73, no. 6, 1965, pp. 573--594. JSTOR, www.jstor.org/stable/1829884.

-   Introduction: "VINER expressed the opinion in 1950 that "there is no way in which the 'height' of a tariff as an index of its restrictive effect can be even approximately measured, or, for that matter, even defined with any degree of significant precision."2 Undaunted by Viner's and others' critical remarks, a long line of investigators, using more or less ingenious methods, have made attempts to compare the height of tariff levels in industrial countries.3 More recently, these inquiries have been given added impetus by the establishment of the European Common Market4 and tariff negotiations undertaken in the framework of the Kennedy round.5 Estimates of the height of national tariff levels are designed to give expression to the restrictive effect of duties on trade flows.6 In a general equilibrium framework, the restrictive effect of a country's tariff can be indicated by the difference between potential and actual trade, when the former refers to trade flows that would take place under ceteris paribus assumptions if the country in question eliminated all of its duties. Tariffs affect the pattern of production and consumption and generally reduce imports and exports under full employment conditions as changes in relative prices associated with the imposition of tariffs lead to resource shifts from export industries to import competing industries. In empirical investigations, however, attention is focused on imports, so that the difference between potential and actual imports is presumed to express the restrictive effect of duties.7 Among the ceteris paribus assumptions, two are of special interest: the assumption of given exchange rates and of given tariffs in other countries. For one thing, the maintenance of balance-of-payments equilibrium would probably necessitate a devaluation in the country that unilaterally reduced its tariffs;8 for another, actual changes in trade flows would depend on the changes that occurred in all the national tariffs. To avoid the complications associated with changing more than one variable, in the following discussion we will consider the restrictive effects of national tariffs under the assumption that exchange rates (and domestic prices) remain unchanged, and we will disregard at the earlier stages of the argument the interaction of tariffs imposed in individual countries." (pg. 573-574)

-   Notes: effective tariffs have been calculated for the United States, the European Common Market, the United Kingdom, Sweden, and Japan. For the tariffs they used from the Brussels Tariff Nomenclature (BTN) which is employed by the EEC for the UK, Sweden and japan. For the United States, tariff categories have been reclassified according to the BTN in *Comparative Tariffs and Trade* they have relied on this compilation while adjusting the results for reductions in duties accomplished in the Dillon round of tariff negotiations. Further, the specific duties applied chiefly in Britain have been expressed in ad valorem equivalents, whereas the common external tariff has been used in the case of the EEC. The tariffs shown for the 4-digit BTN headings have been expressed in terms of the four-digit items in the SITC. Tables with the nominal and effective rates from 1962 are on page 580-582. The paper looks 72 different items as shown in the table. the categories are specific, examples include: thread and yarn, textile fabrics, hosiery, clothing, other textile articles, and so on.

### 19. Ball, David Stafford. "United States Effective Tariffs and Labor's Share." Journal of Political Economy, vol. 75, no. 2, 1967, pp. 183--187. JSTOR, www.jstor.org/stable/1829827.

-   Intro: "ANALYSIS and interpretation of the nature of the tariff schedules of the United States and other developed countries serve two important functions. First, it serves to check the empirical relevance of the factor- proportions theory of trade, which predicts that an economy's relatively scarce factor has incentive to seek protection from international competition. Second, it discloses the nature of the tariff protection that stands between the export industries of the developing countries and the markets of the United States and other developed countries.' tries.' Recent estimates of effective tariff rates, which take into account not only the tariff on imports competitive with an industry's output but also tariffs on the industry's inputs, have increased our knowledge of the protective effect of the tariff systems of some developed countries. This paper offers an interpretation of the pattern of effective protection that differs from those offered heretofore and that appears to be consistent with the results of other research in international trade."

-   Notes: Ball said " Balassa (1965, p. 585) estimated effective tariff rates for thirty-six manufacturing industries in several developed countries, and found that "no definite relationship is shown between labor intensiveness and effective rates of duties" (pg. 184) the data used in the tables are Computed from Balassa's rankings of 1962 U.S. effective tariffs (1966, Table 2, pp. 581- 82), and from rankings of characteristics of the U.S. industries computed from the U.S. Bureau of the Census, Annual Survey of Manufactures, 1962. The 31 industries are Balassa's 36 industries except his industries 48 49 and 51, for which exact analogues could not be found in the U.S. industry data; also Balassa's three leather industries, 26, 35, and 36, have adjacent ranks on effective tariffs (their effective tariffs were 25.3, 25.7, and 24.5 per cent) and were treated as one industry.

### 20. Basevi, Giorgio. "The United States Tariff Structure: Estimates of Effective Rates of Protection of United States Industries of United States Industries and Industrial Labor." The Review of Economics and Statistics, vol. 48, no. 2, 1966, pp. 147--160. JSTOR, www.jstor.org/stable/1924631.

-   Main Point: "This article presents the results of an empirical study of the United States tariff structure, undertaken as an application of the new theory of tariff structures, and designed to throw light on some of the important questions in contemporary tariff discussion, as well as on some older questions about the protective effect of the United States tariff structure. Section I expounds the theory of tariff structures, and develops a formula for calculating effective rates of protection of total value added in particular industries. Section II extends the theory of tariff structures a step further, and develops a formula for calculating effective rates of protection of labor in particular industries. Section III presents the results of two sets of calculations of effective rates of protection for samples of industries, taken from the 1954 and 1958 Census of Manufactures. Section IV contains the results of some regressions designed to test the conclusions previously reached by Beatrice N. Vaccara I on the relationship between tariff protection and employment in various industries. Section V summarizes the findings of my research and relates them to the issues for which they seem to be most relevant." (pg. 147-148).

-   Data: Basevi said "This section presents the results of two sets of calculations of total-rates of protection and labor-rates of protection for various industries. The first calculation was based on input-output data for 1954 and rates of duty collected in 1954, the second, on input-output data for 1958 and rates of duty collected in 1959-1960. The two main sources of data used in the first calculation were Beatrice Vaccara's study and the 1954 Census of Manufacturers.8 Vaccara's study is concerned with the relations between labor intensity (measured both in physical and in value terms) and degree of protection in different industries. However, her measure of degree of protection is based only on duties collected on imports that are substitutes for the industry's output. Thus, because the effect of duties collected on imported inputs are ignored, a true picture is not given of the effective degree of protection afforded each industry by the tariff structure. " (pg. 151). The table (on page 153) holds selective tariff rates and rates of effective protection from a sample of industries in the 1954 census of Manufactures. There are 48 items and they are organized by SIC codes

### 21. Branson, William H. "U.S. Comparative Advantage: Some Further Results." Brookings Papers on Economic Activity\</i\>, vol. 1971, no. 3, 1971, pp. 754--759. JSTOR, www.jstor.org/stable/2534163.

-   Intro: "IN THE LAST ISSUE OF this journal, Helen Junz and I reported the preliminary results of an analysis of the sources of U.S. comparative advantage in trade in manufactured goods. The basic answer was that the U.S. advantage is in commodities whose production uses human capital intensively.' We looked only at data for the mid-1960s, which were developed separately and Hufbauer.2 To study the data, we performed multiple regressions relating net exports by standard international trade classification (SITC) commodity groups to six production characteristics: human capital per man (H), physical capital per man (K), a measure of the presence of economies of scale in production (S), the date at which the commodity first appeared in the U.S. export schedule (P), the ratio of expenditures on research and development to value added (RD), and the fraction of employees in the professional, scientific, and technical categories (T).3 While the earlier results showed fairly clearly the positive relation of net exports to human capital per man and their negative relation to physical capital per man, several discussants suggested that the analysis would be improved if the dependent variable in the regressions were scaled to reflect size of industry. The point is that large industries, all other things equal, are likely to have larger trade surpluses or deficits than small industries. For example, consider a large industry producing commodity A and a small industry producing commodity B, both with exactly the same set of production characteristics. The United States might export \$12 billion and import \$10 billion of good A for a \$2 billion surplus, while if industry B is one-tenth the size of A, the United States would export \$1.2 billion and import \$1.0 billion of B, for a \$200 million surplus. The earlier estimates would be inefficient in that they include no variable that reflects this difference in scale. Several ways to remedy this deficiency have been suggested. One that could be applied with the data already in hand is to use as the dependent variable the ratio of exports to gross trade (exports plus imports) by industry. In the example above, this would give a ratio of exports to gross trade of 0.545 (= 12/22 = 1.2/2.2) for both commodities. This measure is thus scale free, varying between zero and unity, and should improve the estimate"

    -   All of these measures are taken directly from Hufbauer and Keesing except one, the human capital measure. This is calculated by subtracting the median income in 1964 for a worker 25 years old and over with less than an eighth-grade education, \$1,717, from Hufbauer's average wage per industry, and then capitalizing this difference at a 10 percent rate of return. The median income is the weighted average for males and females from U.S. Bureau of the Census, Currenit Population Reports, Series P-60, No. 47, "Income in 1964 of Families and Persons in the United States" (1965) p.39.

-   Underneath Table 1: "Data on U.S. trade by SITC commodity groups are from Organization for Economic Cooperation and Development, Trade by Commodities, Detailed Analysis by Products, Imports, 1964, Series C (OECD), and OECD, Trade by Commodities, Detailed Analysis by Products, Exports, 1964, Series C (OECD). Data on research and development expenditures are from Donald B. Keesing, "The Impact of Research and Development on United States Trade," Journal of Political Economy, Vol. 75 (February 1967), p. 47. All other data are from G. C. Hufbauer, "The Impact of National Characteristics and Technology on the Commodity Composition of Trade in Manufactured Goods," in Raymond Vernon (ed.), The Technology Factoring International Trade, A Conference of the Universities-National Bureau Committee for Economic Research (Columbia University Press for the national Bureau of Economic Research, 1970)" (pg 757)

-   HAVE YOU LOOKED AT THE KEESING AND HUFBAUER PAPERS SEPARATELY? IF NOT, PLEASE TRACK THEM DOWN AND ADD TO THE LIT REVIEW.

### 22. Branson, William H., et al. "Trends in U.S. Trade and Comparative Advantage." Brookings Papers on Economic Activity, vol. 1971, no. 2, 1971, pp. 285--345. JSTOR, www.jstor.org/stable/2534225. Accessed 14 Aug. 2021.

-   Main Point: " In an attempt to illuminate some of the uncertainties concerning the U.S. trade position this paper presents an analytical description of U.S. trade in manufactured goods, drawing on our ongoing research into these topics. It is organized around three questions: What have been the long-term trends in U.S. trade by commodity groups? How has the U.S. trade performance in the 1960s compared with that of other major industrial countries? What is the source of current U.S. comparative advantage in trade? The first section draws on the trade data broken down by the end-use categories employed by the Office of Business Economics (OBE) to review trends in U.S. trade from 1925 to 1970, by seven major end-use aggregates. The second extends the analysis of the U.S. aggregates, drawing on the data published by the Organization for Economic Co-operation and Development (OECD) on trade among the major industrialized countries and on national GNP data in order to compare U.S. output, demand, and trade by major end-use categories with those of other industrial countries in the 1960s. The third section turns to disaggregated data on trade in manufactured goods, reviewing trends in disaggregated OBE end-use groups to observe patterns in trade at the three- and four-digit level. The final section studies the source of U.S. comparative advantage in a cross-section of U.S. trade by two- and three-digit standard international trade classification (SITC) categories." (pg. 286).

-   Data: Table 1 shows net U.S. exports for seven major export end-use categories for the years 1925-70, excluding the war years 1941-45. The Authors organized the data by End-use commodity categories: Total agricultural goods, Fuel and lubricants, Chemicals, others, Capital goods, Consumer goods, Automotive products, other, and total.

### 23. Baldwin, Robert E. "Trade and Employment Effects in the United States of Multilateral Tariff Reductions." The American Economic Review, vol. 66, no. 2, 1976, pp. 142--148. JSTOR, www.jstor.org/stable/1817211.

-   Intro: "This paper summarizes certain aspects of my research into the trade and employment effects in the United States of a significant multilateral reduction in trade-distorting measures by the world's major trading nations. The study differs from earlier investigations into this question such as those by Giorgio Basevi (1968), Stephen Magee (1973), Robert Stern (1964), and Beatrice Vaccara and Walter Salant (1960) in that the industry break- down is much more detailed and the con- sequences of a multilateral tariff reduction on both U.S. export and import-competing industries is taken into account. By estimating not only the net trade and employment effects of a significant tariff reduction in over 350 industries but also in the 50 states and on some 14 occupational groups, it is hoped that the results will be useful for those who are now embarked on the so-called Tokyo round of trade negotiations within the framework of the General Agreement of Tariffs and Trade (GATT). Another novel feature of the study is the estimation of the net employment effects of multilateral tariff cuts under the assumption of flexible exchange rates." (pg. 142)

-   Data Sources: "The trade and tariff data needed for the study are available for 1970 and 1971 from the secretariat of GATT. This organization obtained tariff and trade information on a tariff-line basis from its major trading members and then classified it according to the Brussels Trade Nomenclature (B TN) at a 4-digit level.5 The industry breakdown employed corresponds to the 367-sector delineation of the 1967 sector input-output table prepared by the U.S. Department of Commerce. Intermediate-use coefficients from this study were also employed." (pg. 144) The counties covered are: the US, Japan, Canada, Austria, New Zealand, Finland, Switzerland, Sweden, Norway, and the nine European Community (EC) members: France, Germany, Italy, Belgium, Luxembourg, Denmark, the UK, and Ireland.

### 24. Mutti, John H. "Welfare Effects of Multilateral Tariff Reductions." Southern Economic Journal, vol. 45, no. 3, 1979, pp. 760--772. JSTOR, www.jstor.org/stable/1057475.

-   Intro: "This paper analyzes the economic efficiency effects of tariff concessions made in the Kennedy Round trade negotiations. The static welfare methodology used differs from previous analyses of multilateral tariff reductions by focusing on terms of trade changes. These changes often are incompletely allowed for because the underlying currency appreciations and depreciation necessary to balance unequal shifts in import and export values are ignored. Relative to the traditionally estimated welfare gains from tariff reductions, these terms of trade effects may have a major impact. It is shown that the Kennedy Round cuts may have left the U.S. worse off due to a terms of trade deterioration... Welfare effects from the Kennedy Round negotiations are calculated for four major industrial countries: France, Germany, Japan, and the U.S. The empirical results illustrate that seemingly comparable tariff reductions result in different efficiency effects across countries and that countries within a trading bloc are not affected identically" (pg. 760-761)
-   Notes: the trade figures are taken from OECD summaries of exports and imports by country and commodity for 1963. A condensed summary of the tariff reductions made is provided by UNCTAD. The figures reported for SITC categories 5, 6, 7, and 8 are used to determine the weighted average tariff concessions received by a country.

### 25. Brown, F., & Whalley, J. (1980). General Equilibrium Evaluations of Tariff-Cutting Proposals in the Tokyo Round and Comparisons with More Extensive Liberalisation of World Trade. *The Economic Journal,* *90*(360), 838. <doi:10.2307/2231746>

-   Intro: " In this paper a numerical general equilibrium model of international trade involving major world trading blocs (the United States, Japan, the EEC and the Rest of the World) is used to analyse the effects of alternative tariff-cutting formulate proposed by the major participants in the Tokyo Round negotiations under the GATT at an earlier stage preceding the recent agreement which was initialized in April 1979. We also compare our findings with model experiments involving more extensive forms of world trade liberalisation. Multilateral tariff reductions corresponding to individual country proposals are considered along with a sequence of more wide-ranging trade liberalisation measures on multilateral, bilateral and unilateral bases. The model used is described elsewhere (Whalley, 1978a) and only a brief verbal summary is given here so as to keep the main focus of the paper on results."

-   Notes: The data used is from GATT (1974), Yeats (1976;1977). Data is for the year 1973. The product and industrial classification unites in the general equilibrium trade models are listed in table 1, page 843.

    -   The classifications are:

        -   Agriculture: Meats and Dairy Products, Cereals, Other agricultural products, forestry and fisheries

        -   Mining: coal, oil, natural gas, metallic, non-metallic, and other

        -   manufacturing:

            -   Non-durable goods, prepared foods and kindred products: tear, sugar, coffee, spices, cocoa, alcoholic beverages, other foods, tobacco, appareal and textiles products, paper, printing, publishing, pharmaceuticals and toiletries, other chemical and allied products, petroleum and coal products, rubber and plastics

            -   Durable goods: Lumber, wood and furniture, primary and fabricated metals, stone, glass, Machinery except electrical, electrical machinery, transportation vehicles, scientific and precious instruments, miscellaneous manufacturing

            -   Services: Construction, water transportation, other transportation and comunications, housing services, wholesale and retail trade, finance, insurance, and real estate, other services, government

-   <https://www.jstor.org/stable/pdf/2231746.pdf>

### 26. Cheh, J. H. (1976). A Note on Tariffs, Nontariff Barriers, and Labor Protection in United States Manufacturing Industries. *Journal of Political Economy,* *84*(2), 389-394. <doi:10.1086/260442>

-   Intro: "This note tests empirically whether all United States trade restrictions, both tariff and non-tariff, protect labor in manufacturing industries. The relationship between United States tariffs and labor intensity as measured by either direct labor use or labor cost has been examined by Vaccara (1960) and Basevi (1966). This paper's point of departure lies in taking non-tariff barriers explicitly into account in a "total" measure of protection. Due partly to the success of previous rounds of multilateral tariff negotiations in reducing nominal tariffs, non-tariff barriers to trade have been receiving increasing attention in recent years from economists and policymakers alike. They are emerging as a focal point of discussion in the current Tokyo Round of multilateral tariff negotiations. As Baldwin notes in his study of non-tariff barriers, "the lowering of tariffs has, in effect, been like draining a swamp. The lower water level has revealed all the snags and stumps of non-tariff barriers that still have to be cleared away" (Baldwin 1970, p. 2). Ohlin (1969) has developed the thesis that success with tariff reductions may generate pressures on governments to impose new forms of non-tariff barriers. The increasing importance of non-tariff barriers for the United States in both relative and absolute terms has been noted elsewhere by the author (Cheh 1974a, pp. 328-29)."

-   SOURCES.-Rates of protection in 1964 constructed from Baldwin (1970). Labor use no. of employees per million dollars of value of domestic shipments in 1963; Labor cost = total wages and salaries per hundred dollars of value of domestic shipments in 1963 (constructed from U.S. Bureau of the Census 1966).

-   <https://www.jstor.org/stable/pdf/1831911.pdf>

### 27. Krause, Lawrence B. "United States Imports, 1947-1958." Econometrica, vol. 30, no. 2, 1962, pp. 221--238. JSTOR, www.jstor.org/stable/1910214.

-   Abstract: United States imports of manufactured products during the period 1947 to 1958 are examined in order to investigate the importance of changes in relative prices, ad valorem tariffs, and domestic production as explanatory variables. A cross section technique using first differences of product data over time is employed. Calculations were made after some stratifications of the data in order to illuminate additional aspects of the problem. Variable time lengths were used in the estimating process in an effort to evaluate the effect of time itself on the parameter estimates and also to determine whether peculiarities exist with respect to the particular years involved. The results were interpreted as reflecting institutional changes that have occurred in United States trade policy during this period."

-   Data Source: U.S Dept. of Commerce, *Historical Statistics of the United States*, and U.S. Dept. of Commerce, *Survey of Current Business*

### 28. Krause, Lawrence B. "United States Imports and the Tariff." The American Economic Review, vol. 49, no. 2, 1959, pp. 542--551. JSTOR, www.jstor.org/stable/1816146.

-   Intro: "Since 1934, the stated objective of United States commercial policy has been the stimulation of international trade. The effectiveness of our major vehicle for implementing this policy, the Reciprocal Trade Agreements Program, has often been questioned. In particular, the Congress in its recent inquiry prompted by the proposed extension of the program attempted to determine the effect of tariff reductions on the volume of United States imports.' Unfortunately, the lack of accurate and sufficient observations of all the relevant variables has made it impossible to isolate the effect of tariff reductions from the other factors of import demand. Thus we have no accurate measure of the effect of tariff changes alone on import volume.... If there were two groups of dutiable imports differing only in the existence of tariff reductions in one of the groups, then one could with more certainty attribute behavioral dissimilarities in import volume be- tween the two groups to differences in tariff history. The present study attempts to analyze the effect of tariff changes in this manner. The tariff reductions resulting from the Torquay Agreement in 1951 were selected for investigation. Products having tariff reductions at this time made up one group, hereafter referred to as "the reduced group." A "non-reduced group" was compiled from commodities listed in the tariff schedule as having no tariff reduction at Torquay (or Annecy). Foodstuffs and raw materials were excluded from both groups in order both to avoid the problem of agricultural quotas and to focus attention initially on the more price-elastic manufactured goods. The two groups were made comparable by selecting the non-reduced group, in such a way as to roughly equate it with respect to commodity composition and base value of imports to the reduced group.4 A volume index was computed for each commodity for the years 1952 through 1956 inclusive, the base being the average annual volume of trade in 1949, 1950, and 1951.5" (pg. 542-543).

-   The paper created an index of volume of Imports into the United States of Products whose Tariffs were Reduced by the Torquay Agreement, of Similar products with no tariff reductions and of all finished manufactured imports from 1949-1956.

    -   Data were taken from the following sources: U.S. Bureau of the Census, United States Imports of Merchandise for Consumption, Report No. FT 110, Calendar Years 1949 through 1956. U.S. Bureau of the Census, Schedule A: Statistical Classification of Commodities Imported into the United States (Aug. 1, 1950, edition corrected to May 1, 1952; and Jan. 1, 1954, edition reprinted July, 1957). U.S. Department of State, Analysis of Torquay Protocol of Accession, Schedules, and Related Documents (1951).

### 29. Leamer, Edward E. "The Commodity Composition of International Trade in Manufactures: An Empirical Analysis." Oxford Economic Papers, vol. 26, no. 3, 1974, pp. 350--374. JSTOR, www.jstor.org/stable/2662292.

-   Intro: " THE proliferation of theoretical explanations of the commodity composition of international trade has apparently subsided. Attention seems now to be turning toward endeavors designed to filter the empirically relevant from the empirically irrelevant theories. Four recent substantial papers by Hufbauer (1970), Gruber and Vernon (1970), Baldwin (1971), and Branson and Junz (1971) as well as a long list of shorter works have begun to fill the gap in our empirical understanding of this subject. This paper is meant to be a further step in that direction. We will employ the comparative cross-section regression analysis used by Chenery (1960), Chenery and Taylor (1968), and more recently Gruber and Vernon (1970), Balassa (1969), Keesing (1968), and Keesing and Sherk (1971). Basically, the approach involves regressing trade patterns at a single point in time on country characteristics. This paper is distinguished from those just cited especially by its coverage of country characteristics but also by its level of disaggregation. Special emphasis is allocated to tariffs which have previously been excluded from consideration

-   Data: The data set consists of 1958 trade flows among twelve Atlantic Area countries. They use 28 tariff items and is organized using SITC No.

### 30. Balassa, Bela. "Tariff Protection in Industrial Nations and Its Effects on the Exports of Processed Goods from Developing Countries." The Canadian Journal of Economics / Revue Canadienne D'Economique, vol. 1, no. 3, 1968, pp. 583--594. JSTOR www.jstor.org/stable/133754.

-   "In this paper, I have calculated the nominal and the effective rates of protection in the major industrial countries for twenty-two primary commodities at different levels of processing. Among the industrial countries, estimates have been prepared for the United States, the United Kingdom, the European Common Market, Sweden, and Japan. The investigation includes practically all important primary commodities that are exported by developing countries in processed form, the major exception being petroleum.5 In order to reduce the error possibilities of estimation, I have attempted to use a relatively narrow definition of commodities. This has not been possible, however, in the case of some foodstuffs, such as meat, fruits, and vegetables, where the relevant data for individual commodities are not available.6 Altogether, twenty-two primary commodities have been distinguished: meat, fish, fruits, vegetables, cocoa, leather, groundnuts, kopra, palm-kernel, palm- oil, rubber, wood, pulpwood, wool, cotton, jute, sisal and henequen, iron, copper, aluminum, lead, and zinc. The average number of stages of transformation is three; there are two stages of transformation in seven cases, three stages in eleven instances, and four or more stages in the remainder. To carry out the calculations we need data on input coefficients (the share of material inputs in the value of output) and on nominal tariffs. Whenever possible, reliance has been placed on input coefficients derived from information pertaining to the Common Market countries.7 In other instances I have utilized information on input coefficients provided by UNCTAD, FAO, and GATT, the findings of a study by Heinz Bachmann8 and the results of the 1958 US census.9 Rates of nominal tariffs for the year 1962 have been taken from national tariff schedules and expressed uniformly on a CIF basis." (pg. 586-587)

-   The first table uses the weighted averages of nominal and Effective Tariffs and imports from less developed areas in the major industrial countries: the US, UK, Common Market, Sweden, Japan, and Industrial countries in 1964. The second table uses import data of selected commodities into industrial counties from less developed areas (countries include:US, Canada, Commonwealth Uk, Non-commonwealth UK, Common Market, Continental EFTA, Sweden, Japan, and industrial countries as a whole). The source used was the United Nations, Commodity Trade Statistics, 1964.

### 31. Baldwin, R. E., and T. Murray. "MFN Tariff Reductions and Developing Country Trade Benefits Under the GSP." *The Economic Journal*, vol. 87, no. 345, 1977, pp. 30--46. *JSTOR*, www.jstor.org/stable/2231831.

-   A key proposal of the first United Nations Conference on Trade and Development (UNCTAD) held in I1964 was that developed countries should grant preferential tariff treatment on imports of manufactured and semi-manufactured products originating in developing countries - the so-called " Generalized System of Preferences" (GSP). Up to the present time Australia, Austria, Canada, the European Community (EEC), Finland, Japan, New Zealand, Norway, Sweden, Switzerland and the United States have introduced preferential tariff arrangements.' As these various schemes begin to give some promise of meaningful trade concessions to the developing nations (the so-called beneficiaries), the developed countries (donors) have launched upon a new round of multilateral trade negotiations under the auspices of the General Agreement on Tariffs and Trade (GATT). It is too early to predict the outcome of these negotiations, but the objective of significant reductions in tariff levels is a plausible result. In general, the developing countries, in so far as their views are reflected in UNCTAD documents, have viewed these multilateral trade negotiations with considerable concern.2 Substantial most-favoured-nation (MFN) tariff cuts would seem to hold the prospect of an adverse effect on the beneficiary nations by eroding the margins of preference established under the GSP schemes. While this is obviously true, there are other considerations some of which would benefit the developing countries. For example, not all developing countries nor all manufactured goods are covered by the various preference arrangements. In all likelihood the MFN cuts would cover a broader range of products and definitely would benefit some developing countries presently excluded from the GSP. Moreover, the preference schemes embody limits on the volume of trade which will benefit from GSP tariff rates; MFN tariff reductions, on the other hand, provide more favorable access to world markets for unlimited trade volumes.3 The purpose of this paper is to determine in quantitative terms whether the benefits of the GSP are so limited that deep MFN cuts would be more beneficial to the developing nations than maintaining the GSP preferential tariff advantages. In making this determination we first estimate the benefits of the GSP under the assumption that no MFN cuts take place; we then estimate the costs and benefits to the developing countries of a 50 % across-the-board MFN cut introduced in conjunction with the GSP. To facilitate calculations, we limit attention to the three major GSP schemes - those of the United States, the EEC, and Japan - which together account for some go % of donor country imports of manufactured products from developing countries." (pg. 30-31)

-   Imports of GSP products are from 1971. The data consist of 40 products that range from dolls to calculating machines.

### 32. Finger, J. M. "Gatt Tariff Concessions and the Exports of Developing Countries--United States Concessions at the Dillon Round." *The Economic Journal*, vol. 84, no. 335, 1974, pp. 566--575. *JSTOR*, www.jstor.org/stable/2231040.

-   " AT the 1960-61 GATT tariff conference (The Dillon Round) the United States negotiated with the European Economic Community and 11 other developed countries (DC) as well as with six less developed countries (LDC) (Cambodia, Haiti, India, Israel, Pakistan and Peru) and agreed to reduce its duties on products covering some \$2 billion of imports in 1960. While this 20 % reduction of tariffs on some 20 % of dutiable imports was small compared with the 35 % cut on almost 55 % of dutiable imports achieved in the more recent Kennedy Round, they were more extensive, both in terms of the magnitude of the reductions and extent of import coverage, than the reductions achieved in any of the previous five GATT rounds except the first, in Geneva in 1947."

-   Data: " A complete revision of United States tariff nomenclature which went into effect in mid-1963 made the collection of "before" (1960) and "after" (1965) data extremely difficult." Though considerable effort was expended in collecting data, the sample included only 9 % of the trade on the concessions list (see line 1, Table I).2 Quantity and value of imports data were taken from the United States Census Bureau publications cited in the references, and tariff rates from the State Department report. Changes in value, quantity and unit value for each item were expressed as percentages of the average of their 1960 and 1965 levels, and average changes for the reduced and non-reduced groups were then computed using 1960 plus 1965 value of imports as weights.3" (pg. 567)

### 33. Finger, J. M. "Trade and Domestic Effects of the Offshore Assembly Provision in the U.S. Tariff." *The American Economic Review*, vol. 66, no. 4, 1976, pp. 598--611. *JSTOR*, www.jstor.org/stable/1806700.

-   Main Point: " The object of this paper is to estimate the static impact of the OAP on domestic economic activity (in assembly and in production of components) and on the balance of trade. Estimates of the effect on domestic economic welfare of the OA1P will also be presented. The effect on investment flows will be taken into account indirectly by the supply parameters of the model, but will not be explicitly estimated. To measure balance of payments rather than simply the balance-of-trade impact, an estimate of the effect of OAP trade on the profit remittances of foreign subsidiaries would also be required."

-   Data: " The basic data used in the study were from the Census Bureau's report of the total and dutiable values of OAP imports. These data, plus data for "Directly Competitive Imports" (non-OAP imports in those 7-digit TSUS categories in which there were OAP imports)10 provided the measures of imports of foreign assembly and of foreign components, and of C, the components' input-output coefficient.'1 Components are identified in the data and therefore in the results only by the industry in which they are used, and not by the industry in which they are produced. It follows that labor-output coefficients could not be identified, and the estimates of output displacement could not be translated into employment displacement estimates." (pg. 605-606)

### 34. Finger, J. M., and A. J. Yeats. "Effective Protection by Transportation Costs and Tariffs: A Comparison of Magnitudes." *The Quarterly Journal of Economics*, vol. 90, no. 1, 1976, pp. 169--176. *JSTOR*, www.jstor.org/stable/1886094.

-   Transportation costs tend to protect domestic producers from foreign competition-as do such artificial barriers as import quotas, tariffs, etc. Yet international economic analysis often (indeed, nearly always) assumes away the effects of transportation costs. This creates and perhaps in part stems from the presumption that transportation costs are small relative to other barriers.' Another possible explanation for the virtual nonexistence of empirical analysis of transport costs is that they are to a large extent market prices that, unlike tariffs, are outside of the direct control of policy makers. However, within the context of the models commonly used to analyze international trade problems, transport costs, like tariffs, are an exogenous variable, and their exclusion is justifiable only if they are small relative to tariffs, or if they are stable. A survey of the literature, however, indicated that there have been few attempts to measure even nominal shipping rates,2 and apparently no studies comparing effective rates of protection from tariffs and transportation costs. Since relevant data are available, the magnitude of the barrier imposed by transportation costs in international trade need not be left entirely to conjecture. The purpose of this paper is to compare nominal and effective protection for domestic products stemming from United States tariffs and from international transportation and insurance costs on imports. In making these comparisons, the differential impact of these factors on imports from developed and developing countries is noted. In addition, recent changes in the levels of tariffs and transportation costs are examined, and the policy implications of this study's findings are discussed. " (pg. 169-170)

-   Data: "Information on transportation and insurance costs for United States imports was taken primarily from a 1965 Census Bureau- Tariff Commission sample of approximately 13,000 shipments.3 These data were originally drawn in order to convert f.o.b. United States import figures to c.i.f. values in preparation for the Kennedy Round negotiations. This source provided c.i.f.-f.o.b. ratios (i.e., the ad valorem equivalent to transportation and insurance costs) computed from records of actual shipments. Since the data on individual transactions were then averaged for some 200 products or product groupings, actual transportation costs for any one particular exporter to the United States may be higher or lower than the figures shown." (pg. 170)

### 35. Keesing, Donald B. "The Impact of Research and Development on United States Trade." *Journal of Political Economy*, vol. 75, no. 1, 1967, pp. 38--48. *JSTOR*, www.jstor.org/stable/1829544.

-   Intro: "NUMBER of people have argued that what gives the United States its ability to compete in world markets despite its high wages is its ability to supply a steady flow of new products.' New products can be attributed partly to research and development. This article tests the hypothesis that R & D activity is associated with American competitive ability in manufacturing industries, and also tests this hypothesis against other hypotheses advanced to explain American trade patterns. One would expect, at most, an imperfect correlation between American competitive ability and R & D activity in each industry. Exports of new products consisting of military and space equipment are not freely permitted. Probably not all R & D affects exports in the industry that performs the R & D; some affect other industries. The link between R & D activity and new products is far from routine, and other countries engage in R & D in competition with the United States.2 In addition, the available indicators of R & D and U.S. competitive ability are far from perfect. U.S. competitive ability is measured throughout this study by 1962 U.S. exports in each industry as a percentage of the total 1962 exports of the leading industrial countries known as the Group of Ten (the United States, United Kingdom, Federal Republic of Germany, France, Italy, Belgium, Netherlands, Sweden, Canada, and Japan).' Indicators of R & D in each industry are taken from data published by the National Science Foundation.4 In every case, the information is limited to R & D performed by industrial companies, either for themselves or under contract.5 Data on R & D expenditure by industry are seriously flawed because R & D is classified according to the main industry of the company performing the task, though firms that perform R & D characteristically spread their efforts over many product fields.6 Information on applied R & D expenditure by product field is available only for a rather unsatisfactory set of product fields.7 The best of the available indicators of R & D activity is perhaps scientists and engineers in R & D as a percentage of the labor force of each industry, classified according to the industry of the establishment in which people work." (pg. 38-39)

-   DATA: Break down of all the data used is in Appendix 1 and 2 on page 46 and 47. The author used data collected from the National Science Foundation on 18 different industries: Aircraft, Office machinery, Drugs, Other machinery, Instruments, Chemicals (except drugs), electrical equipment, rubber products, motor vehicles, Petroleum refining, Fabricated metal products, non-ferrous metals, paper and allied products, stone clay and glass products, other transport equipment, Lumber and wood products, Textile mil products, Primary ferrous metals. They collected import and export data from all of these industries and are based on the US Bureau of Census (1963, Table 1-C)

### 36. Hufbauer, Gary Clyde "The Impact of National Characteristics and Technology on the Commodity Composition of Trade in Manufactured Goods," *National Bureau of Economic Research*, vol. The Technology Factor in International Trade, 1970, pp 145-231. *NBER*, ISBN: 0-87014-208-9

-   Intro: "It was once fashionable to hear about a "notorious lag" between international trade theory and other branches of economic analysis. The lag may still exist, but in the meantime new theories have surfaced--- theories which explain export and import patterns in terms of "technological" variables. These theories often perform well when applied to a single group of commodities or a limited range of countries. But how do they fare when pitted against one another on common commodities and countries? To answer this question is an ambitious task, and the evaluation offered here has several limitations: it deals with the broad sweep of trade theories, often in rashly over-simplified form; it confines itself to manufactured goods; and it examines only the commodity composition of trade. Our principal goal has been to develop empirical measures to test hypotheses in the broadest possible terms, and this goal has been pursued at the expense of theoretical analysis. We are not much interested in the impact of natural resource location on trade flows; therefore the analysis has been limited to manufactured goods. The problems of a dual economy are ignored although these problems may significantly affect trade flows. Nor are we concerned with the forces determining the growth and fluctuation of trade. Instead the focus is on commodity composition.'" (page 145-146)

-   DATA: "Statistical information on trade and economic structure circa 1965 was gathered for a carefully selected group of twenty-four countries, contributing some 90 per cent of the manufactured exports from nonsocialist countries. The twenty-four nations are listed in Table 2. Eliminated in the selection process were nations with relatively small (and hence probably erratic) manufactured exports; nations belonging to the socialist camp (because of closely regulated trade and lack of data); and nations specializing in manufactured exports requiring nontransportable natural resources.5 Because of this preselection process, the trade theories perform better than if applied to a more haphazard collection of nations6. Furthermore, each theory receives, in the alternative, the benefit of one ad hoc exclusion: the one country most at variance with the predictions of each theory is dropped in order to obtain an alternative evaluation of the twenty-three "best" nations....." (pg. 150-151)

-   Notes: All 7 theories are listed in table 1 (pg. 147-148). Counties include: Canada, US, Austria, Belgium, Denmark, France, Germany, Italy, Netherlands, Norway, Sweden, UK, Australia, Japan, Israel, Portugal, Spain, Yugoslavia, Mexico, Hong Kong, India, Korea, Pakistan, and Taiwan. Table 2 shows the characteristics of all these countries' 1965 Exports. Table 3 shows the haracteristics of all these countries' 1965 Imports. Table A-2 (pg. 218-220) shows the characteristics of Traded goods enumerated in the two-digit and three-digit SITC.

-   <https://www.nber.org/system/files/chapters/c3381/c3381.pdf>

### 37. Edward E. Leamer, James Levinsohn, Chapter 26 "International trade theory: The evidence, Handbook of International Economics", Elsevier, Volume 3,1995, Pages 1339-1394, ISSN 1573-4404, ISBN 9780444815477burgees

-   Publisher Summary: "This chapter focuses on the international trade theory. It discusses the Ricardian and the Ricardo--Viner models. These models point to technological differences as the source of international comparative advantage. A simple Ricardian model has one input, labor, which is assumed to be mobile across the two sectors of the economy, but internationally immobile. The Ricardo--Viner model introduces into the model two additional factors that are sector-specific. This gives curvature to the production possibilities curve and also allows international commerce to affect the distribution of income. Although there is little or no direct empirical support for these simple models, there is nonetheless growing awareness that technological differences are a natural consequence of economic isolation and play a role in the integration process, following an economic liberalization. The chapter provides an overview of the Heckscher--Ohlin model and discusses the Rybcyzinski theorem and the Stolper--Samuelson theorem. It also reviews the studies of the Heckscher--Ohlin model based on cross country comparisons."

-   (Part of) Intro: "we turn to reviewing the recent em- pirical literature on "testing" trade theories and "estimating" the relative im- portance of different sources of comparative advantage. In our review, we have placed heavier emphasis on newer work and refer the reader to Deardorff (1984) for a review of older work. We have also tried to go beyond just reviewing the lit- erature and, on several occasions, suggest possibly fruitful but as yet unexplored research topics and strategies. This review is organized around the sources of comparative advantage ordered by intellectual chronology: technological dif- ferences in Section 2, factor proportions in Section 3, competitive strategies in Section 4, demand biases in Section 5 and distance in Section 6. The Appendix provides a brief discussion of some of the data sources often used in the empiri- cal international trade literature as well as possibly useful but less well exploited data sources." (pg. 1343)

-   Data Sources (pg. 1388- 1390):

    -   United Nations Trade Data Tapes: provides the bilateral trade flows at the 4 and/or 5 digit SITC levels.

    -   Highly detailed information regarding the current structure of U.S. trade, by commodity and by partner, as well as a host of other information, is distributed on CD-ROM by the U.S. Department of Commerce

    -   Data on trade and labor by industry for the United States are also found in the National Bureau of Economic Research (NBER) Trade and Immigration data set. This data set contains trade, employment and output data for 450 U.S. manufacturing industries by 4-digit SIC code from 1958-86. Variables include employment, unionization, import, exports, firm size, industry concentration as well as many other related data.

    -   Data on tariffs and non-tariff barriers are compiled by the GATT and UNC- TAD. UNCTAD produces the TNT data base. This data base provides nominal tariff rates by harmonized tariff code as well as non-tariff measures. The non- tariff measure available is a weighted coverage ratio, where the weights used are trade values.

    -   U.S. Bureau of Labor Statistics maintains a fairly comprehensive data base on import and export price indexes for U:S. industries by SIC code.

-   <https://reader.elsevier.com/reader/sd/pii/S1573440405800061?token=994E0EB18D58227C7E2653BCA866D22725312CF8081A97827E0F944A8ADB6BE8CDBF57C2A68F052A621C8056F8FE92B9&originRegion=us-east-1&originCreation=20210820052541>

## How to continue the Lit Review

The literature review focuses on finding studies that uses empirical trade data from 1930-1988 in the United States. Above, I highlighted the topic of the paper, what data the used, the countries involved, where they got the data, and if mentioned the products used.

To continue the Literature Review, you can pick any of the papers listed in the Literature review and search up them up on Google Scholar. You can find potential papers in the reference area of these articles or you can look at where the paper is cited in and find more papers there.

Below is a list of papers that would be a great place to pick up the research.

-   Alan V. Deardorff, \*Testing trade theories and predicting trade flows\*,Chapter 10, Handbook of International Economics, Elsevier, Volume 1, 1984, Pages 467-517, ISSN 1573-4404, ISBN 9780444867926,

-   Finger, J. M., and A. J. Yeats. "Effective Protection by Transportation Costs and Tariffs: A Comparison of Magnitudes." *The Quarterly Journal of Economics*, vol. 90, no. 1, 1976, pp. 169--176. *JSTOR*, www.jstor.org/stable/1886094.

-   Finger, J. M. "Trade and Domestic Effects of the Offshore Assembly Provision in the U.S. Tariff." *The American Economic Review*, vol. 66, no. 4, 1976, pp. 598--611. *JSTOR*, www.jstor.org/stable/1806700.

-   Edward E. Leamer, James Levinsohn, Chapter 26 "International trade theory: The evidence, Handbook of International Economics", Elsevier, Volume 3,1995, Pages 1339-1394, ISSN 1573-4404, ISBN 9780444815477burgees

## Removed:

1.  Bergstrand, Jeffrey H. "The Gravity Equation in International Trade: Some Microeconomic Foundations and Empirical Evidence." The Review of Economics and Statistics, vol. 67, no. 3, 1985, pp. 474--481. JSTOR, www.jstor.org/stable/1925976.

    -   Reason: Paper focuses on a generalized gravity equation and the "empirical evidence" he used does not specify an exact country.

2.  Chenery, Hollis B., and Lance Taylor. "Development Patterns: Among Countries and Over Time." The Review of Economics and Statistics, vol. 50, no. 4, 1968, pp. 391--416. JSTOR, www.jstor.org/stable/1926806.

    -   reason: There is very little trade data in the paper, it is not the main focus. However, the export data that is used in the paper is from the United Nations Yearbook of International Trade Statistics , various years. Data is laid out in table 11 on page 414.

3.  PARZYCH, KENNETH M. An Analysis Of Export Trade Under The Webb-pomerene Act Of 1918, University of Connecticut, Ann Arbor, 1970. ProQuest, <https://libezproxy.syr.edu/login?url=https://www.proquest.com/dissertations-theses/analysis-export-trade-under-webb-pomerene-act/docview/302515727/se-2?accountid=14214.>

    -   reason: uses data from 1880-1920

4.  Baldwin, Robert E. "The Political Economy of Trade Policy." The Journal of Economic Perspectives, vol. 3, no. 4, 1989, pp. 119--135. JSTOR, www.jstor.org/stable/1942913.

    -   No empirical data just policy

5.  Burgess, David F. "Tariffs and Income Distribution: Some Empirical Evidence for the United States." Journal of Political Economy, vol. 84, no. 1, 1976, pp. 17--45. JSTOR, www.jstor.org/stable/1830169.

    -   The paper focuses on an equation and does not state where he got the data. The evidence portion of the paper is also very small and is more of an example of how the equation works.

6.  Kowalczyk, Carsten and Davis, Donald. "8. Tariff Phase-Outs: Theory and Evidence from GATT and NAFTA". The Regionalization of the World Economy, edited by Jeffrey A. Frankel, Chicago: University of Chicago Press, 2007, pp. 227-258

    -   Data collection starts after 1988

7.  Alan V. Deardorff, \*Testing trade theories and predicting trade flows\*,Chapter 10, Handbook of International Economics, Elsevier, Volume 1, 1984, Pages 467-517, ISSN 1573-4404, ISBN 9780444867926,

    -   The paper does not use any empirical data but instead reviews other paper's data. I moved it to the how to continue the lit review continuation section.
